### ISSUE TITLE
图片输入大小

### ISSUE THREAD

**Issue by zdaiot** [opteroncx/MDDM#2]
当我输入图片大小是1920x1080大小时，报错如下：
```
Traceback (most recent call last):
  File "test_all.py", line 58, in <module>
    elapsed_time = demoire(root,image,model,out_path)
  File "test_all.py", line 35, in demoire
    clear = model(im_input)
  File "/data4/zhaodali/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data4/zhaodali/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data4/zhaodali/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data6/zhaodali/Code/MDDM/model6_dfe_nl2.py", line 434, in forward
    clean = b1 + b2 + b3 + b4 + b5 + b6
RuntimeError: The size of tensor a (1080) must match the size of tensor b (1088) at non-singleton dimension 3
```

请问这个怎么解决？

**Comment by opteroncx** [comment]
默认输入大小是1024x1024或者512x512的，因为有好几个2x下采样和上采样，你需要保证你输入的图片长宽是2的5次方的整数倍

**Comment by zdaiot** [comment]
好的，谢谢啦
